# Generated by Django 5.1.3 on 2024-11-24 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='professor',
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_1', models.BooleanField(default=None, null=True)),
                ('resposta_2', models.BooleanField(default=None, null=True)),
                ('resposta_3', models.BooleanField(default=None, null=True)),
                ('resposta_4', models.TextField(blank=True, null=True)),
                ('resposta_5', models.BooleanField(default=None, null=True)),
                ('resposta_6', models.BooleanField(default=None, null=True)),
                ('resposta_7', models.BooleanField(default=None, null=True)),
                ('resposta_8', models.BooleanField(default=None, null=True)),
                ('resposta_9', models.TextField(blank=True, null=True)),
                ('resposta_10', models.BooleanField(default=None, null=True)),
                ('resposta_11', models.TextField(blank=True, null=True)),
                ('resposta_12', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('alunos', models.ManyToManyField(to='setup.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.professor')),
            ],
        ),
    ]
