# Generated by Django 5.1.3 on 2024-11-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_professor_remove_aluno_professor_resposta_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
